const arr = [
    {
        name: '服务器',
        id: 1,
        position: { x: 100, y: 200 },
        group: 'one',
        groupName: '管理员',
    },
    {
        name: '交换机',
        id: 2,
        position: { x: 100, y: 200 },
        group: 'two',
        groupName: "中心"
    },
    {
        name: '主机1',
        id: 3,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',

    },
    {
        name: '主机2',
        id: 4,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',

    },
    {
        name: '主机3',
        id: 5,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '主机4',
        id: 6,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',

    },
    {
        name: '主机5',
        id: 7,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',

    },
    {
        name: '显示器1',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '显示器2',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '显示器3',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '显示器4',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '显示器5',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '显示器6',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '显示器7',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '显示器8',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },
    {
        name: '显示器9',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'three',
        groupName: '用户',
    },


    {
        name: '主机6',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '主机7',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '主机8',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器1',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器2',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器3',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器4',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器5',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器6',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器7',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器8',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
    {
        name: '显示器9',
        id: 8,
        position: { x: 100, y: 200 },
        group: 'four',
        groupName: '用户2',
    },
]

export default arr